### ISSUE TITLE
Definir estrutura de branches a ser utilizada

### ISSUE THREAD

**Issue by roziscoding** [Webschool-io/Bot-Telegram-BeMEAN#22]
Precisaremos de uma estrutura de branches bem definida para desenvolvimento, testes e produção; essa estrutura não deverá interferir na estrutura atual do bot

**Comment by rjmunhoz** [comment]
Sugestão: utilizar a mesma estrutura do boilerplate [plugabble-telegram-bot](https://github.com/rjmunhoz/plugabble-telegram-bot);
Como a maioria dos comandos a serem implementados funcionam apenas com texto, a estrutura deve ser suficiente para darmos início à refatoração
